### ISSUE TITLE
Access to the repositories of the organizations.

### ISSUE THREAD

**Issue by otanim** [beerpay/beerpay.io#17]
I'm unable to add projects from my own organization.
"To refresh" my account I've deactivated my account and tried authorize again, but now I can't even include the projects from the my own account of GitHub.

**Comment by colkito** [comment]
Hi @otanim!
I saw in your GitHub profile that your Organizations are hidden.
Please, remember that we use your public info to get your repositories, and only your own repositories, no forked. (for now)

If you want to show your Organizations, this post of GitHub could help you https://help.github.com/articles/publicizing-or-hiding-organization-membership/

Let me know if this solve your problem.
Greetings!

**Comment by otanim** [comment]
@colkito I did so as it was said in the article.
But it doesn't help.

**Comment by colkito** [comment]
Great @otanim, now you will need to update your access token (because was created without access to your organizations) or just *grant access* to Beerpay to your organizations. 
To do that just:
1. Follow this link https://github.com/settings/applications
2. Click in the Beerpay application
3. In the *Organization access* section, click in the *Grant access* button for the organizations you want.

Let me know if this solve your problem.
Greetings!

**Comment by otanim** [comment]
@colkito , I've already granted access to my organization, have a look:
![image](https://cloud.githubusercontent.com/assets/7108843/16488488/d70cb2e8-3ee1-11e6-9e58-7a88984c1958.png)

**Comment by colkito** [comment]
@otanim please try now, and tell us, it should be fixed!

**Comment by otanim** [comment]
@colkito I've just logged out, I've tried to log in and it's work perfect !
Thanks :blush:

**Comment by colkito** [comment]
Great @otanim!
Thanks for your feedback!
