### ISSUE TITLE
Can't see my organization's repositories

### ISSUE THREAD

**Issue by Thatkookooguy** [beerpay/beerpay.io#25]
Already tried everything in #17 . Nothing worked.

revoked access, logged out, logged in.

Nothing works. I keep seeing my own repositories but no organization repositories.

**[Kibibit](https://github.com/Kibibit)** is a **public organization**, and **[kibibit-code-editor](https://github.com/Kibibit/kibibit-code-editor)** is an **open-source project**. So, everything should go according to your flow.

any help would be appreciated

**Comment by colkito** [comment]
hi @Thatkookooguy!
I've checking your account and your public GitHub info. The problem is simple to fix.
Your orgs are private (https://api.github.com/users/Thatkookooguy/orgs), you could follow this comment https://github.com/beerpay/beerpay.io/issues/17#issuecomment-229532638 or this link https://help.github.com/articles/publicizing-or-hiding-organization-membership/ in order to show/hide your orgs from your public profile.

Please, let me know if this solve your problem.
Cheers!

**Comment by Thatkookooguy** [comment]
thanks, it worked :-)
